const close = "https://ik.imagekit.io/qjxemaiij5/Chest-Box.svg";
const open = "https://ik.imagekit.io/qjxemaiij5/Chest-open-Box.svg";

const landAllCycles = {
  7: {
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:Land (COMMON).",
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      greet: "Congratulations !",
      title1: "Animation Plugin v1",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz."`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    cryptoNinjaNftDuelPack: {
      icon: close,
      openBox: open,
      title: "CRYPTONINJA",
      title1: "NFTDuel card Pack",
      cycle: "7",
      greet: "Congratulations !",
      message1: " You had won CryptoNinja NFTDuel card Pack.",
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    cryptoNinjaNftDuelWhiteList: {
      icon: close,
      openBox: open,
      title: "CRYPTONINJA",
      title1: "NFTDuel card Whitelist",
      greet: "Congratulations !",
      message1: ` You had won "CryptoNinja NFTDuel card WHITELIST".`,
      message2: "* You can use this Whitelist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDualBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel BOOSTER",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel Booster ”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA WEARABLES",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "* An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      greet: "Congratulations !",
      title1: "",
      message1: " You had won IN-APP CURRENCY.",
      message2:
        "* An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  8: {
    xanaPenpenzAllowlist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      title1: "Allowlist",
      cycle: 8,
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2: "※ You can use this Whitelist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },

    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "(Type-B)",
      cycle: "8",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz (Type-B)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "(Type-A)",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables (Type-A)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "In-App currency".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  9: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "(Type-B)",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz (Type-B)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "(Type-A)",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables (Type-A)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  10: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "(Type-B)",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz (Type-B)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "(Type-A)",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables (Type-A)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  11: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  12: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:Penpenz",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: ` You had won "XANA:Penpenz".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  13: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:Penpenz",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: ` You had won "XANA:Penpenz".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  14: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:Penpenz",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: ` You had won "XANA:Penpenz".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  15: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:Penpenz",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: ` You had won "XANA:Penpenz".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:GENESIS".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this Whitelist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  16: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:Penpenz",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: ` You had won "XANA:Penpenz".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  17: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:Penpenz",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: ` You had won "XANA:Penpenz".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:GENESIS".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  18: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:Penpenz",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: ` You had won "XANA:Penpenz".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  19: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:Penpenz",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: ` You had won "XANA:Penpenz".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  20: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:Penpenz",
      title1: "",
      cycle: 8,
      greet: "Congratulations !",
      message1: ` You had won "XANA:Penpenz".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Plugin v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can't be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (Pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      greet: "Congratulations !",
      title1: "(single)",
      message1: `You had won "NFTDuel card (single)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  cycles: [
    { key: "cycle20", title: "Cycle 20", cycle: "20" },
    { key: "cycle19", title: "Cycle 19", cycle: "19" },
    { key: "cycle18", title: "Cycle 18", cycle: "18" },
    { key: "cycle17", title: "Cycle 17", cycle: "17" },
    { key: "cycle16", title: "Cycle 16", cycle: "16" },
    { key: "cycle15", title: "Cycle 15", cycle: "15" },
    { key: "cycle14", title: "Cycle 14", cycle: "14" },
    { key: "cycle13", title: "Cycle 13", cycle: "13" },
    { key: "cycle12", title: "Cycle 12", cycle: "12" },
    { key: "cycle11", title: "Cycle 11", cycle: "11" },
    { key: "cycle10", title: "Cycle 10", cycle: "10" },
    { key: "cycle9", title: "Cycle 9", cycle: "9" },
    { key: "cycle8", title: "Cycle 8", cycle: "8" },
    { key: "cycle7", title: "Cycle 7", cycle: "7" },
  ],
};

export default landAllCycles;
