const ruffleContractMainnet = {
  abi: [
    {
      type: "event",
      name: "AppliedUnstake",
      inputs: [
        {
          type: "address",
          name: "staker",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "stakeIndex",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256[]",
          name: "geneTokenIds",
          internalType: "uint256[]",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "CampaignEdited",
      inputs: [
        {
          type: "uint256",
          name: "startTime",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "endTime",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "CampaignReward",
      inputs: [
        {
          type: "uint256",
          name: "campaignId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "collection",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "from",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "to",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "user",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "CampaignStarted",
      inputs: [
        {
          type: "uint256",
          name: "rewardCount",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "startTime",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "endTime",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Initialized",
      inputs: [
        {
          type: "uint8",
          name: "version",
          internalType: "uint8",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          type: "address",
          name: "previousOwner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "newOwner",
          internalType: "address",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Paused",
      inputs: [
        {
          type: "address",
          name: "account",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RufflStart",
      inputs: [
        {
          type: "address",
          name: "user",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "campaignId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "totalTickets",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RuffleJoined",
      inputs: [
        {
          type: "address",
          name: "user",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "campaignId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "start",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "end",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "StakeEnd",
      inputs: [
        {
          type: "address",
          name: "staker",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "stakeIndex",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256[]",
          name: "geneTokenIds",
          internalType: "uint256[]",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "StakeStart",
      inputs: [
        {
          type: "address",
          name: "staker",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "stakeIndex",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256[]",
          name: "geneTokenIds",
          internalType: "uint256[]",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Unpaused",
      inputs: [
        {
          type: "address",
          name: "account",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "function",
      stateMutability: "pure",
      outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
      name: "_leaf",
      inputs: [
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "string", name: "rarity", internalType: "string" },
        { type: "uint256", name: "size", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "pure",
      outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
      name: "_leafWinner",
      inputs: [
        { type: "uint256", name: "limit", internalType: "uint256" },
        { type: "address", name: "user", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "callback",
      inputs: [
        { type: "uint256[]", name: "ids", internalType: "uint256[]" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [
        { type: "uint256", name: "newClaimedTickets", internalType: "uint256" },
      ],
      name: "callbackJoinRuffle",
      inputs: [
        { type: "uint256", name: "totalTickets", internalType: "uint256" },
        { type: "address", name: "user", internalType: "address" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
      name: "campaignRewardsRoot",
      inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "claimStakingReward",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256", name: "limit", internalType: "uint256" },
        { type: "bytes32[]", name: "proof", internalType: "bytes32[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "editLootBox",
      inputs: [
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "emergencyWithdraw",
      inputs: [{ type: "address", name: "receiver", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address[]", name: "", internalType: "address[]" }],
      name: "getActiveStakers",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "address", name: "collection", internalType: "address" },
      ],
      name: "getCampaignDetails",
      inputs: [
        { type: "uint256", name: "_campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "newClaimedTickets", internalType: "uint256" },
      ],
      name: "getClaimableTickets",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "uint256", name: "ruffleTime", internalType: "uint256" },
      ],
      name: "getCurrentCampaignDetails",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "", internalType: "uint256" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
      name: "getGlobals",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "getIsClaimable",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
        { type: "uint256", name: "stakeId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "getRewardClaimable",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        {
          type: "tuple",
          name: "",
          internalType: "struct GlobalsAndUtils.Stake",
          components: [
            { type: "uint256", name: "stakedAt", internalType: "uint256" },
            { type: "uint256", name: "tokenId", internalType: "uint256" },
            {
              type: "address",
              name: "landCollection",
              internalType: "address",
            },
            {
              type: "uint256[]",
              name: "genesisTokenIds",
              internalType: "uint256[]",
            },
            { type: "uint256", name: "size", internalType: "uint256" },
            { type: "string", name: "rarity", internalType: "string" },
            { type: "uint256", name: "xTickets", internalType: "uint256" },
          ],
        },
      ],
      name: "getStake",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
        { type: "uint256", name: "stakeId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        {
          type: "tuple",
          name: "",
          internalType: "struct GlobalsAndUtils.UnStake",
          components: [
            { type: "uint256", name: "stakedAt", internalType: "uint256" },
            { type: "uint256", name: "appliedAt", internalType: "uint256" },
            { type: "uint256", name: "unStakedAt", internalType: "uint256" },
            { type: "uint256", name: "tokenId", internalType: "uint256" },
            {
              type: "address",
              name: "landCollection",
              internalType: "address",
            },
            {
              type: "uint256[]",
              name: "genesisTokenIds",
              internalType: "uint256[]",
            },
            { type: "uint256", name: "size", internalType: "uint256" },
            { type: "string", name: "rarity", internalType: "string" },
            { type: "uint256", name: "xTickets", internalType: "uint256" },
            { type: "bool", name: "isAppliedFor", internalType: "bool" },
          ],
        },
      ],
      name: "getUnStake",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
        { type: "uint256", name: "stakeId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "getUserStakesIds",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "getUserUnStakesIds",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "getWinningTickIds",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "initialize",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "isRequested",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isRewardOpen",
      inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isUserWinner",
      inputs: [
        { type: "uint256", name: "limit", internalType: "uint256" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "bytes32[]", name: "proof", internalType: "bytes32[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isWhitelisted",
      inputs: [
        { type: "string", name: "rarity", internalType: "string" },
        { type: "uint256", name: "size", internalType: "uint256" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "bytes32[]", name: "proof", internalType: "bytes32[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [
        { type: "uint256", name: "newClaimedTickets", internalType: "uint256" },
      ],
      name: "joinRuffle",
      inputs: [
        { type: "uint256", name: "totalTickets", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "owner",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "pause",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "paused",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "newClaimedTickets", internalType: "uint256" },
      ],
      name: "perDayXTicketsUserClaimable",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "renounceOwnership",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "rewardLootBox",
      inputs: [
        { type: "uint256", name: "end", internalType: "uint256" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setCampaignDetails",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "address", name: "collection", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setCampaignId",
      inputs: [{ type: "uint256", name: "_id", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setCampaignWinners",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "bytes32", name: "_root", internalType: "bytes32" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setLandAndGenesis",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setLandRoot",
      inputs: [{ type: "bytes32", name: "_root", internalType: "bytes32" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setOracleAddress",
      inputs: [{ type: "address", name: "_add", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setRewardCanBeClaim",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "bool", name: "status", internalType: "bool" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setTickEraned",
      inputs: [
        { type: "string", name: "rarity", internalType: "string" },
        { type: "uint256", name: "size", internalType: "uint256" },
        { type: "uint256", name: "amount", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setTotalTicketsEarned",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256", name: "totalTickets", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setUserJoinRuffle",
      inputs: [
        { type: "address[]", name: "_addresses", internalType: "address[]" },
        { type: "uint256[]", name: "_start", internalType: "uint256[]" },
        { type: "uint256[]", name: "_end", internalType: "uint256[]" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256[]", name: "_totalTickets", internalType: "uint256[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "startLootBox",
      inputs: [
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "startLootBox",
      inputs: [
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
        { type: "address", name: "_awardCollection", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "ticketIdUsed",
      inputs: [
        { type: "uint256", name: "", internalType: "uint256" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "totalStakedAmount",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "totalStakedNFT",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "transferOwnership",
      inputs: [{ type: "address", name: "newOwner", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "unpaused",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "updateRewardCollection",
      inputs: [
        { type: "address", name: "_collection", internalType: "address" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "userClaimable",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
        { type: "uint256", name: "stakeId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "userStakedAmount",
      inputs: [{ type: "address", name: "", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "userStakedAmountNFT",
      inputs: [{ type: "address", name: "", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "start", internalType: "uint256" },
        { type: "uint256", name: "end", internalType: "uint256" },
      ],
      name: "userXTicketRange",
      inputs: [
        { type: "address", name: "", internalType: "address" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "winningTixketIdExist",
      inputs: [
        { type: "uint256", name: "", internalType: "uint256" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
    },
    { type: "receive", stateMutability: "payable" },
  ],
  address: "0x1432a91aeefF4418CBF5fDE3f91b5C9502148C7a",
};

const ruffleContractTestnet = {
  abi: [
    {
      type: "event",
      name: "AppliedUnstake",
      inputs: [
        {
          type: "address",
          name: "staker",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "stakeIndex",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256[]",
          name: "geneTokenIds",
          internalType: "uint256[]",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "CampaignEdited",
      inputs: [
        {
          type: "uint256",
          name: "startTime",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "endTime",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "CampaignReward",
      inputs: [
        {
          type: "uint256",
          name: "campaignId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "collection",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "from",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "to",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "user",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "CampaignStarted",
      inputs: [
        {
          type: "uint256",
          name: "rewardCount",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "startTime",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "endTime",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Initialized",
      inputs: [
        {
          type: "uint8",
          name: "version",
          internalType: "uint8",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          type: "address",
          name: "previousOwner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "newOwner",
          internalType: "address",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Paused",
      inputs: [
        {
          type: "address",
          name: "account",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RufflStart",
      inputs: [
        {
          type: "address",
          name: "user",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "campaignId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "totalTickets",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RuffleJoined",
      inputs: [
        {
          type: "address",
          name: "user",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "campaignId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "start",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "end",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "StakeEnd",
      inputs: [
        {
          type: "address",
          name: "staker",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "stakeIndex",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256[]",
          name: "geneTokenIds",
          internalType: "uint256[]",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "StakeStart",
      inputs: [
        {
          type: "address",
          name: "staker",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "stakeIndex",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256[]",
          name: "geneTokenIds",
          internalType: "uint256[]",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Unpaused",
      inputs: [
        {
          type: "address",
          name: "account",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "function",
      stateMutability: "pure",
      outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
      name: "_leaf",
      inputs: [
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "string", name: "rarity", internalType: "string" },
        { type: "uint256", name: "size", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "pure",
      outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
      name: "_leafWinner",
      inputs: [
        { type: "uint256", name: "limit", internalType: "uint256" },
        { type: "address", name: "user", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "callback",
      inputs: [
        { type: "uint256[]", name: "ids", internalType: "uint256[]" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [
        { type: "uint256", name: "newClaimedTickets", internalType: "uint256" },
      ],
      name: "callbackJoinRuffle",
      inputs: [
        { type: "uint256", name: "totalTickets", internalType: "uint256" },
        { type: "address", name: "user", internalType: "address" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
      name: "campaignRewardsRoot",
      inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "claimStakingReward",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256", name: "limit", internalType: "uint256" },
        { type: "bytes32[]", name: "proof", internalType: "bytes32[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "editLootBox",
      inputs: [
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "emergencyWithdraw",
      inputs: [{ type: "address", name: "receiver", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address[]", name: "", internalType: "address[]" }],
      name: "getActiveStakers",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "address", name: "collection", internalType: "address" },
      ],
      name: "getCampaignDetails",
      inputs: [
        { type: "uint256", name: "_campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "newClaimedTickets", internalType: "uint256" },
      ],
      name: "getClaimableTickets",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "uint256", name: "ruffleTime", internalType: "uint256" },
      ],
      name: "getCurrentCampaignDetails",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "", internalType: "uint256" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
      name: "getGlobals",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "getIsClaimable",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
        { type: "uint256", name: "stakeId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "getRewardClaimable",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        {
          type: "tuple",
          name: "",
          internalType: "struct GlobalsAndUtils.Stake",
          components: [
            { type: "uint256", name: "stakedAt", internalType: "uint256" },
            { type: "uint256", name: "tokenId", internalType: "uint256" },
            {
              type: "address",
              name: "landCollection",
              internalType: "address",
            },
            {
              type: "uint256[]",
              name: "genesisTokenIds",
              internalType: "uint256[]",
            },
            { type: "uint256", name: "size", internalType: "uint256" },
            { type: "string", name: "rarity", internalType: "string" },
            { type: "uint256", name: "xTickets", internalType: "uint256" },
          ],
        },
      ],
      name: "getStake",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
        { type: "uint256", name: "stakeId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        {
          type: "tuple",
          name: "",
          internalType: "struct GlobalsAndUtils.UnStake",
          components: [
            { type: "uint256", name: "stakedAt", internalType: "uint256" },
            { type: "uint256", name: "appliedAt", internalType: "uint256" },
            { type: "uint256", name: "unStakedAt", internalType: "uint256" },
            { type: "uint256", name: "tokenId", internalType: "uint256" },
            {
              type: "address",
              name: "landCollection",
              internalType: "address",
            },
            {
              type: "uint256[]",
              name: "genesisTokenIds",
              internalType: "uint256[]",
            },
            { type: "uint256", name: "size", internalType: "uint256" },
            { type: "string", name: "rarity", internalType: "string" },
            { type: "uint256", name: "xTickets", internalType: "uint256" },
            { type: "bool", name: "isAppliedFor", internalType: "bool" },
          ],
        },
      ],
      name: "getUnStake",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
        { type: "uint256", name: "stakeId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "getUserStakesIds",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "getUserUnStakesIds",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "getWinningTickIds",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "initialize",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "isRequested",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isRewardOpen",
      inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isUserWinner",
      inputs: [
        { type: "uint256", name: "limit", internalType: "uint256" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "bytes32[]", name: "proof", internalType: "bytes32[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isWhitelisted",
      inputs: [
        { type: "string", name: "rarity", internalType: "string" },
        { type: "uint256", name: "size", internalType: "uint256" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "bytes32[]", name: "proof", internalType: "bytes32[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [
        { type: "uint256", name: "newClaimedTickets", internalType: "uint256" },
      ],
      name: "joinRuffle",
      inputs: [
        { type: "uint256", name: "totalTickets", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "owner",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "pause",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "paused",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "newClaimedTickets", internalType: "uint256" },
      ],
      name: "perDayXTicketsUserClaimable",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "renounceOwnership",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "rewardLootBox",
      inputs: [
        { type: "uint256", name: "end", internalType: "uint256" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setCampaignDetails",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "address", name: "collection", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setCampaignId",
      inputs: [{ type: "uint256", name: "_id", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setCampaignWinners",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "bytes32", name: "_root", internalType: "bytes32" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setLandAndGenesis",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setLandRoot",
      inputs: [{ type: "bytes32", name: "_root", internalType: "bytes32" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setOracleAddress",
      inputs: [{ type: "address", name: "_add", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setRewardCanBeClaim",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "bool", name: "status", internalType: "bool" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setTickEraned",
      inputs: [
        { type: "string", name: "rarity", internalType: "string" },
        { type: "uint256", name: "size", internalType: "uint256" },
        { type: "uint256", name: "amount", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setTotalTicketsEarned",
      inputs: [
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256", name: "totalTickets", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setUserJoinRuffle",
      inputs: [
        { type: "address[]", name: "_addresses", internalType: "address[]" },
        { type: "uint256[]", name: "_start", internalType: "uint256[]" },
        { type: "uint256[]", name: "_end", internalType: "uint256[]" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
        { type: "uint256[]", name: "_totalTickets", internalType: "uint256[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "startLootBox",
      inputs: [
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "startLootBox",
      inputs: [
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "uint256", name: "rewardCount", internalType: "uint256" },
        { type: "address", name: "_awardCollection", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "ticketIdUsed",
      inputs: [
        { type: "uint256", name: "", internalType: "uint256" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "totalStakedAmount",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "totalStakedNFT",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "transferOwnership",
      inputs: [{ type: "address", name: "newOwner", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "unpaused",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "updateRewardCollection",
      inputs: [
        { type: "address", name: "_collection", internalType: "address" },
        { type: "uint256", name: "campaignId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "userClaimable",
      inputs: [
        { type: "address", name: "stakeOwner", internalType: "address" },
        { type: "uint256", name: "stakeId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "userStakedAmount",
      inputs: [{ type: "address", name: "", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "userStakedAmountNFT",
      inputs: [{ type: "address", name: "", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "start", internalType: "uint256" },
        { type: "uint256", name: "end", internalType: "uint256" },
      ],
      name: "userXTicketRange",
      inputs: [
        { type: "address", name: "", internalType: "address" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "winningTixketIdExist",
      inputs: [
        { type: "uint256", name: "", internalType: "uint256" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
    },
    { type: "receive", stateMutability: "payable" },
  ],
  address: "0x50a5db6b8304e65249d7eA5ea42229ab6e6D72ad",
};

export const RuffleContract =
  process.env.NEXT_PUBLIC_NETWORK_TYPE === "testnet"
    ? ruffleContractTestnet
    : ruffleContractMainnet;
