const TreasureContractMainnet = {
  abi: [
    { type: "constructor", stateMutability: "nonpayable", inputs: [] },
    { type: "error", name: "ApprovalCallerNotOwnerNorApproved", inputs: [] },
    { type: "error", name: "ApprovalQueryForNonexistentToken", inputs: [] },
    { type: "error", name: "ApprovalToCurrentOwner", inputs: [] },
    { type: "error", name: "ApproveToCaller", inputs: [] },
    { type: "error", name: "BalanceQueryForZeroAddress", inputs: [] },
    { type: "error", name: "InvalidQueryRange", inputs: [] },
    { type: "error", name: "MintToZeroAddress", inputs: [] },
    { type: "error", name: "MintZeroQuantity", inputs: [] },
    { type: "error", name: "OwnerQueryForNonexistentToken", inputs: [] },
    { type: "error", name: "TransferCallerNotOwnerNorApproved", inputs: [] },
    { type: "error", name: "TransferFromIncorrectOwner", inputs: [] },
    {
      type: "error",
      name: "TransferToNonERC721ReceiverImplementer",
      inputs: [],
    },
    { type: "error", name: "TransferToZeroAddress", inputs: [] },
    {
      type: "event",
      name: "AdminTransfer",
      inputs: [
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
        {
          type: "address",
          name: "to",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Approval",
      inputs: [
        {
          type: "address",
          name: "owner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "approved",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ApprovalForAll",
      inputs: [
        {
          type: "address",
          name: "owner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "operator",
          internalType: "address",
          indexed: true,
        },
        {
          type: "bool",
          name: "approved",
          internalType: "bool",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BaseURI",
      inputs: [
        { type: "string", name: "uri", internalType: "string", indexed: false },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Burn",
      inputs: [
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Claim",
      inputs: [
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "gasFee",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ClaimForAnimation",
      inputs: [
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "genesisId",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ClaimForVoicePlugin",
      inputs: [
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "genesisId",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ClaimRewardOther",
      inputs: [
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Mint",
      inputs: [
        {
          type: "uint256",
          name: "start",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "end",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "total",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "to",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "MintWithTokenURI",
      inputs: [
        {
          type: "address",
          name: "collection",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: true,
        },
        {
          type: "address",
          name: "minter",
          internalType: "address",
          indexed: false,
        },
        {
          type: "string",
          name: "tokenURI",
          internalType: "string",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          type: "address",
          name: "previousOwner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "newOwner",
          internalType: "address",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "PurchaseNFT",
      inputs: [
        {
          type: "uint256",
          name: "from",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "to",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "price",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "paid",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "seller",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "_roundId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "buyer",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Transfer",
      inputs: [
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: true,
        },
        { type: "address", name: "to", internalType: "address", indexed: true },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    { type: "fallback", stateMutability: "payable" },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "TransferFromAdmin",
      inputs: [
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "address", name: "to", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "addAllowAddress",
      inputs: [{ type: "address", name: "_add", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "approve",
      inputs: [
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "balanceOf",
      inputs: [{ type: "address", name: "owner", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "baseURI",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "burnAdmin",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "payable",
      outputs: [],
      name: "buyBox",
      inputs: [
        { type: "uint256", name: "_roundId", internalType: "uint256" },
        { type: "uint256", name: "limit", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "payable",
      outputs: [],
      name: "claimReward",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "claimRewardAnimation",
      inputs: [
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "uint256", name: "genesisToken", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "payable",
      outputs: [],
      name: "claimRewardOther",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "claimRewardVoicePlugin",
      inputs: [
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "uint256", name: "genesisToken", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "payable",
      outputs: [],
      name: "claimRewardXeta",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "delegates",
      inputs: [{ type: "bytes4", name: "", internalType: "bytes4" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        {
          type: "tuple",
          name: "",
          internalType: "struct ERC721A.TokenOwnership",
          components: [
            { type: "address", name: "addr", internalType: "address" },
            { type: "uint64", name: "startTimestamp", internalType: "uint64" },
            { type: "bool", name: "burned", internalType: "bool" },
          ],
        },
      ],
      name: "explicitOwnershipOf",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        {
          type: "tuple[]",
          name: "",
          internalType: "struct ERC721A.TokenOwnership[]",
          components: [
            { type: "address", name: "addr", internalType: "address" },
            { type: "uint64", name: "startTimestamp", internalType: "uint64" },
            { type: "bool", name: "burned", internalType: "bool" },
          ],
        },
      ],
      name: "explicitOwnershipsOf",
      inputs: [
        { type: "uint256[]", name: "tokenIds", internalType: "uint256[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bytes", name: "", internalType: "bytes" }],
      name: "funcSignatures",
      inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "getApproved",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "getNumberOfboxesSold",
      inputs: [
        { type: "uint256", name: "currentTime", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "_roundId", internalType: "uint256" },
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "uint256", name: "price", internalType: "uint256" },
        { type: "uint256", name: "userPurchaseLimit", internalType: "uint256" },
        { type: "uint256", name: "maxSupply", internalType: "uint256" },
        { type: "uint256", name: "supply", internalType: "uint256" },
        { type: "bool", name: "iswhiteList", internalType: "bool" },
      ],
      name: "getRoundDetails",
      inputs: [
        { type: "uint256", name: "currentTime", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        { type: "uint256", name: "startTime", internalType: "uint256" },
        { type: "uint256", name: "endTime", internalType: "uint256" },
        { type: "uint256", name: "price", internalType: "uint256" },
        { type: "uint256", name: "userPurchaseLimit", internalType: "uint256" },
        { type: "uint256", name: "maxSupply", internalType: "uint256" },
        { type: "uint256", name: "supply", internalType: "uint256" },
        { type: "bool", name: "iswhiteList", internalType: "bool" },
      ],
      name: "getSpecificRoundDetails",
      inputs: [{ type: "uint256", name: "_roundId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "getUserBoxCount",
      inputs: [
        { type: "uint256", name: "_roundId", internalType: "uint256" },
        { type: "address", name: "_add", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isApprovedForAll",
      inputs: [
        { type: "address", name: "owner", internalType: "address" },
        { type: "address", name: "operator", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isUserWhiteListed",
      inputs: [
        { type: "uint256", name: "_roundId", internalType: "uint256" },
        { type: "address", name: "_add", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "minCostXeta",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "minGasCost",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [
        { type: "uint256", name: "", internalType: "uint256" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
      name: "mint",
      inputs: [
        { type: "address", name: "to_", internalType: "address" },
        { type: "uint256", name: "countNFTs_", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "mintAndBurn",
      inputs: [{ type: "address", name: "to_", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "name",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "owner",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "ownerOf",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "registerUser",
      inputs: [
        { type: "address", name: "_add", internalType: "address" },
        { type: "uint256", name: "_roundId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "registerUsers",
      inputs: [
        { type: "address[]", name: "_add", internalType: "address[]" },
        { type: "uint256", name: "_roundId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "removeAllowAddress",
      inputs: [{ type: "address", name: "_add", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "removeUser",
      inputs: [
        { type: "address", name: "_add", internalType: "address" },
        { type: "uint256", name: "_roundId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "removeUsers",
      inputs: [
        { type: "address[]", name: "_add", internalType: "address[]" },
        { type: "uint256", name: "_roundId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "renounceOwnership",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "safeTransferFrom",
      inputs: [
        { type: "address", name: "from", internalType: "address" },
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "safeTransferFrom",
      inputs: [
        { type: "address", name: "from", internalType: "address" },
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "bytes", name: "_data", internalType: "bytes" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setApprovalForAll",
      inputs: [
        { type: "address", name: "operator", internalType: "address" },
        { type: "bool", name: "approved", internalType: "bool" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setAuthor",
      inputs: [{ type: "address", name: "_add", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setBaseURI",
      inputs: [{ type: "string", name: "baseURI_", internalType: "string" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setMinGasCost",
      inputs: [{ type: "uint256", name: "_cost", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setMinGasCostXeta",
      inputs: [{ type: "uint256", name: "_cost", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "supportsInterface",
      inputs: [{ type: "bytes4", name: "interfaceId", internalType: "bytes4" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "symbol",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "tokenURI",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "tokensOfOwner",
      inputs: [{ type: "address", name: "owner", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "tokensOfOwnerIn",
      inputs: [
        { type: "address", name: "owner", internalType: "address" },
        { type: "uint256", name: "start", internalType: "uint256" },
        { type: "uint256", name: "stop", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "totalSupply",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "transferFrom",
      inputs: [
        { type: "address", name: "from", internalType: "address" },
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "transferOwnership",
      inputs: [{ type: "address", name: "newOwner", internalType: "address" }],
    },
    { type: "receive", stateMutability: "payable" },
  ],
  address: "0x422Ab9E31cC5cA8CA8266986FF4cd8fD18b68F1e",
};

const TreasureContractTestnet = {
  abi: [
    { type: "constructor", stateMutability: "nonpayable", inputs: [] },
    { type: "error", name: "ApprovalCallerNotOwnerNorApproved", inputs: [] },
    { type: "error", name: "ApprovalQueryForNonexistentToken", inputs: [] },
    { type: "error", name: "ApprovalToCurrentOwner", inputs: [] },
    { type: "error", name: "ApproveToCaller", inputs: [] },
    { type: "error", name: "BalanceQueryForZeroAddress", inputs: [] },
    { type: "error", name: "InvalidQueryRange", inputs: [] },
    { type: "error", name: "MintToZeroAddress", inputs: [] },
    { type: "error", name: "MintZeroQuantity", inputs: [] },
    { type: "error", name: "OwnerQueryForNonexistentToken", inputs: [] },
    { type: "error", name: "TransferCallerNotOwnerNorApproved", inputs: [] },
    { type: "error", name: "TransferFromIncorrectOwner", inputs: [] },
    {
      type: "error",
      name: "TransferToNonERC721ReceiverImplementer",
      inputs: [],
    },
    { type: "error", name: "TransferToZeroAddress", inputs: [] },
    {
      type: "event",
      name: "AdminTransfer",
      inputs: [
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
        {
          type: "address",
          name: "to",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Approval",
      inputs: [
        {
          type: "address",
          name: "owner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "approved",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ApprovalForAll",
      inputs: [
        {
          type: "address",
          name: "owner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "operator",
          internalType: "address",
          indexed: true,
        },
        {
          type: "bool",
          name: "approved",
          internalType: "bool",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "BaseURI",
      inputs: [
        { type: "string", name: "uri", internalType: "string", indexed: false },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Burn",
      inputs: [
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Claim",
      inputs: [
        {
          type: "uint256[]",
          name: "tokenId",
          internalType: "uint256[]",
          indexed: false,
        },
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "gasFee",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ClaimForAnimation",
      inputs: [
        {
          type: "uint256[]",
          name: "tokenId",
          internalType: "uint256[]",
          indexed: false,
        },
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "genesisId",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ClaimForVoicePlugin",
      inputs: [
        {
          type: "uint256[]",
          name: "tokenId",
          internalType: "uint256[]",
          indexed: false,
        },
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "genesisId",
          internalType: "uint256",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ClaimRewardXenyToken",
      inputs: [
        {
          type: "uint256[]",
          name: "tokenId",
          internalType: "uint256[]",
          indexed: false,
        },
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Mint",
      inputs: [
        {
          type: "uint256",
          name: "start",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "end",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "total",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "to",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "MintWithTokenURI",
      inputs: [
        {
          type: "address",
          name: "collection",
          internalType: "address",
          indexed: true,
        },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: true,
        },
        {
          type: "address",
          name: "minter",
          internalType: "address",
          indexed: false,
        },
        {
          type: "string",
          name: "tokenURI",
          internalType: "string",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          type: "address",
          name: "previousOwner",
          internalType: "address",
          indexed: true,
        },
        {
          type: "address",
          name: "newOwner",
          internalType: "address",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "PurchaseNFT",
      inputs: [
        {
          type: "uint256",
          name: "from",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "to",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "price",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "uint256",
          name: "paid",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "seller",
          internalType: "address",
          indexed: false,
        },
        {
          type: "uint256",
          name: "_roundId",
          internalType: "uint256",
          indexed: false,
        },
        {
          type: "address",
          name: "buyer",
          internalType: "address",
          indexed: false,
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Transfer",
      inputs: [
        {
          type: "address",
          name: "from",
          internalType: "address",
          indexed: true,
        },
        { type: "address", name: "to", internalType: "address", indexed: true },
        {
          type: "uint256",
          name: "tokenId",
          internalType: "uint256",
          indexed: true,
        },
      ],
      anonymous: false,
    },
    { type: "fallback", stateMutability: "payable" },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "TransferFromAdmin",
      inputs: [
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "address", name: "to", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "addAllowAddress",
      inputs: [{ type: "address", name: "_add", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "approve",
      inputs: [
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "balanceOf",
      inputs: [{ type: "address", name: "owner", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "baseURI",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "burnAdmin",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "payable",
      outputs: [],
      name: "buyBox",
      inputs: [
        { type: "uint256", name: "_roundId", internalType: "uint256" },
        { type: "uint256", name: "limit", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "payable",
      outputs: [],
      name: "claimReward",
      inputs: [
        { type: "uint256[]", name: "tokenId", internalType: "uint256[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "claimRewardAnimation",
      inputs: [
        { type: "uint256[]", name: "tokenId", internalType: "uint256[]" },
        { type: "uint256", name: "genesisToken", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "claimRewardVoicePlugin",
      inputs: [
        { type: "uint256[]", name: "tokenId", internalType: "uint256[]" },
        { type: "uint256", name: "genesisToken", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "payable",
      outputs: [],
      name: "claimRewardXenyToken",
      inputs: [
        { type: "uint256[]", name: "tokenId", internalType: "uint256[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "payable",
      outputs: [],
      name: "claimRewardXeta",
      inputs: [
        { type: "uint256[]", name: "tokenId", internalType: "uint256[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "delegates",
      inputs: [{ type: "bytes4", name: "", internalType: "bytes4" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        {
          type: "tuple",
          name: "",
          internalType: "struct ERC721A.TokenOwnership",
          components: [
            { type: "address", name: "addr", internalType: "address" },
            { type: "uint64", name: "startTimestamp", internalType: "uint64" },
            { type: "bool", name: "burned", internalType: "bool" },
          ],
        },
      ],
      name: "explicitOwnershipOf",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [
        {
          type: "tuple[]",
          name: "",
          internalType: "struct ERC721A.TokenOwnership[]",
          components: [
            { type: "address", name: "addr", internalType: "address" },
            { type: "uint64", name: "startTimestamp", internalType: "uint64" },
            { type: "bool", name: "burned", internalType: "bool" },
          ],
        },
      ],
      name: "explicitOwnershipsOf",
      inputs: [
        { type: "uint256[]", name: "tokenIds", internalType: "uint256[]" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bytes", name: "", internalType: "bytes" }],
      name: "funcSignatures",
      inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "getApproved",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "getUserBoxCount",
      inputs: [
        { type: "uint256", name: "_roundId", internalType: "uint256" },
        { type: "address", name: "_add", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isApprovedForAll",
      inputs: [
        { type: "address", name: "owner", internalType: "address" },
        { type: "address", name: "operator", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "isUserWhiteListed",
      inputs: [
        { type: "uint256", name: "_roundId", internalType: "uint256" },
        { type: "address", name: "_add", internalType: "address" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "minCostXeta",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "minGasCost",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [
        { type: "uint256", name: "", internalType: "uint256" },
        { type: "uint256", name: "", internalType: "uint256" },
      ],
      name: "mint",
      inputs: [
        { type: "address", name: "to_", internalType: "address" },
        { type: "uint256", name: "countNFTs_", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "mintAndBurn",
      inputs: [{ type: "address", name: "to_", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "name",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "owner",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "address", name: "", internalType: "address" }],
      name: "ownerOf",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "removeAllowAddress",
      inputs: [{ type: "address", name: "_add", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "renounceOwnership",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "safeTransferFrom",
      inputs: [
        { type: "address", name: "from", internalType: "address" },
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "safeTransferFrom",
      inputs: [
        { type: "address", name: "from", internalType: "address" },
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
        { type: "bytes", name: "_data", internalType: "bytes" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setApprovalForAll",
      inputs: [
        { type: "address", name: "operator", internalType: "address" },
        { type: "bool", name: "approved", internalType: "bool" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setAuthor",
      inputs: [{ type: "address", name: "_add", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setBaseURI",
      inputs: [{ type: "string", name: "baseURI_", internalType: "string" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setMinGasCost",
      inputs: [{ type: "uint256", name: "_cost", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "setMinGasCostXeta",
      inputs: [{ type: "uint256", name: "_cost", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "bool", name: "", internalType: "bool" }],
      name: "supportsInterface",
      inputs: [{ type: "bytes4", name: "interfaceId", internalType: "bytes4" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "symbol",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "string", name: "", internalType: "string" }],
      name: "tokenURI",
      inputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "tokensOfOwner",
      inputs: [{ type: "address", name: "owner", internalType: "address" }],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
      name: "tokensOfOwnerIn",
      inputs: [
        { type: "address", name: "owner", internalType: "address" },
        { type: "uint256", name: "start", internalType: "uint256" },
        { type: "uint256", name: "stop", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "view",
      outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
      name: "totalSupply",
      inputs: [],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "transferFrom",
      inputs: [
        { type: "address", name: "from", internalType: "address" },
        { type: "address", name: "to", internalType: "address" },
        { type: "uint256", name: "tokenId", internalType: "uint256" },
      ],
    },
    {
      type: "function",
      stateMutability: "nonpayable",
      outputs: [],
      name: "transferOwnership",
      inputs: [{ type: "address", name: "newOwner", internalType: "address" }],
    },
    { type: "receive", stateMutability: "payable" },
  ],
  address: "0x326Cae76A11d85b5c76E9Eb81346eFa5e4ea7593",
};

export const TreasureContract =
  process.env.NEXT_PUBLIC_NETWORK_TYPE === "testnet"
    ? TreasureContractTestnet
    : TreasureContractMainnet;
