const close = "https://ik.imagekit.io/qjxemaiij5/Chest-Box.svg";
const open = "https://ik.imagekit.io/qjxemaiij5/Chest-open-Box.svg";

const allCycles = {
  1: {
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: "You have won LAND : COMMON.",
      message2: "Do you want to claim? (Claims must be paid for gasfee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: "You have won XANA:GENESIS NFT.",
      message2: "Do you want to claim? (Claims must be paid for gasfee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    avatar: {
      icon: close,
      openBox: open,
      title: "RARE AVATAR ITEM",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won “Rare Avatar Item”`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      title1: "",
      greet: "Congratulations !",
      message1: "You have won IN-APP CURRENCY.",
      message2:
        " Do you want to claim the item ? Official announcement on distribution will be made shortly.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    deemoWhitelist: {
      icon: close,
      openBox: open,
      title: "DEEMO WHITELIST",
      title1: "",
      greet: "Congratulations !",
      message1: "You have won DEEMO WHITELIST.",
      message2:
        "Do you want to claim the item ? The timing of exercising the whitelist right will be announced from the official later.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    landWhiteList: {
      icon: close,
      openBox: open,
      title: "LAND WHITELIST",
      title1: "",
      greet: "Congratulations !",
      message1: "You have won LAND WHITELIST.",
      message2:
        "Do you want to claim the item ? The timing of exercising the whitelist right will be announced from the official later.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  2: {
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won LAND : COMMON.",
      message2: "Do you want to claim? (Claims must be paid for gasfee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:GENESIS.",
      message2: "Do you want to claim? (Claims must be paid for gasfee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Voice PLUGIN v1",
      greet: "Congratulations !",
      message1: "",
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation PLUGIN v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    landVipDiscount: {
      icon: close,
      openBox: open,
      title: "LAND VIP DISCOUNT",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won LAND VIP DISCOUNT.",
      message2:
        "*We will be announcing shortly regarding exercising the rights for discount.",

      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    landWhiteList: {
      icon: close,
      openBox: open,
      title: "LAND WHITELIST",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won LAND WHITELIST.",
      message2:
        "*We will be announcing shortly regarding exercising the rights for discount.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    avatar: {
      icon: close,
      openBox: open,
      title: "RARE AVATAR ITEM",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won “Rare Avatar Item”`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      title1: "",
      greet: "Congratulations !",
      message1: "You had won IN-APP CURRENCY.",
      message2: "※ We will be announcing regarding the distribution shortly.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  3: {
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won LAND : COMMON.",
      message2: "Do you want to claim? (Claims must be paid for gasfee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    landVipDiscount: {
      icon: close,
      openBox: open,
      title: "LAND VIP DISCOUNT",
      title1: "Next Sale",
      greet: "Congratulations !",
      message1: " You had won LAND VIP DISCOUNT.",
      message2:
        "*We will be announcing shortly regarding exercising the rights for discount.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:GENESIS.",
      message2: "Do you want to claim? (Claims must be paid for gasfee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Voice Batch v1",
      greet: "Congratulations !",
      message1: "",
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "Animation Batch v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    astroboyPack: {
      icon: close,
      openBox: open,
      title: "ASTROBOY X JAPAN",
      title1: "Next Series Pack",
      greet: "Congratulations !",
      message1: `You had won “ASTROBOY X JAPAN Next Series Pack”`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    astroboyWhiteList: {
      icon: close,
      openBox: open,
      title: "ASTROBOY X JAPAN",
      title1: "Next Series WHITELIST",
      greet: "Congratulations !",
      message1: " You had won WHITELIST.",
      message2:
        "*We will be announcing shortly regarding the timing of exercising the whitelist rights.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    avatar: {
      icon: close,
      openBox: open,
      title: "RARE AVATAR ITEM",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won “Rare Avatar Item”`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won IN-APP CURRENCY.",
      message2: "※ We will be announcing regarding the distribution shortly.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  4: {
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won LAND : COMMON.",
      message2: "Do you want to claim? (Claims must be paid for gasfee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:GENESIS.",
      message2: "Do you want to claim? (Claims must be paid for gasfee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Batch v1",
      greet: "Congratulations !",
      message1: "",
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Animation Batch v1",
      greet: "Congratulations !",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    astroboyPack: {
      icon: close,
      openBox: open,
      title: "ASTROBOY X JAPAN",
      title1: "Next Series Pack",
      greet: "Congratulations !",
      message1: `You had won “ASTROBOY X JAPAN Next Series Pack”`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    astroboyWhiteList: {
      icon: close,
      openBox: open,
      title: "ASTROBOY X JAPAN",
      title1: "Next Series WHITELIST",
      greet: "Congratulations !",
      message1: " You had won WHITELIST.",
      message2:
        "※  We will be announcing shortly regarding the timing of exercising the whitelist rights.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    cryptoNinjaNftDuelWhiteList: {
      icon: close,
      openBox: open,
      title: "CRYPTONINJA",
      title1: "NFTDuel card WHITELIST",
      greet: "Congratulations !",
      message1: " You had won CryptoNinja NFTDuel card WHITELIST.",
      message2:
        "※ We will be announcing shortly regarding the timing of exercising the whitelist rights.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    avatar: {
      icon: close,
      openBox: open,
      title: "RARE AVATAR ITEM",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won “Rare Avatar Item”`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won IN-APP CURRENCY.",
      message2: "※ We will be announcing regarding the distribution shortly.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  5: {
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:Land (COMMON).",
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:GENESIS.",
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: "",
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      greet: "Congratulations !",
      title1: "Animation Plugin v1",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    astroboyOkayamaPack: {
      icon: close,
      openBox: open,
      title: "ASTROBOY X JAPAN",
      title1: "Okayama Pack",
      greet: "Congratulations !",
      message1: "You had won ASTROBOY X JAPAN ( Okayama ) PACK.",
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      title1: "WHITELIST",
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2: "※ You can use this Whitelist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    cryptoNinjaNftDuelWhiteList: {
      icon: close,
      openBox: open,
      title: "CRYPTONINJA",
      title1: "NFTDuel card Whitelist",
      greet: "Congratulations !",
      message1: " You had won CryptoNinja NFTDuel card WHITELIST.",
      message2: "※ You can use this Whitelist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    avatar: {
      icon: close,
      openBox: open,
      title: "RARE AVATAR ITEM",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won “Rare Avatar Item”`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      greet: "Congratulations !",
      title1: "",
      message1: " You had won IN-APP CURRENCY.",
      message2:
        "※ An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  6: {
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:Land (COMMON).",
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:GENESIS.",
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: "",
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaGenesisAnimation: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      greet: "Congratulations !",
      title1: "Animation Plugin v1",
      message1:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      message2: "",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    collaborationTshirtWhitlist: {
      icon: close,
      openBox: open,
      title: "COLLABORATION",
      title1: " T-Shirts WhiteList",
      greet: "Congratulations !",
      message1: `You had won Collaboration T-Shirts WHITELIST`,
      message2:
        "※ An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },

    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      title1: "WHITELIST",
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2: "※ You can use this Whitelist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    cryptoNinjaNftDuelWhiteList: {
      icon: close,
      openBox: open,
      title: "CRYPTONINJA",
      title1: "NFTDuel card Whitelist",
      greet: "Congratulations !",
      message1: " You had won CryptoNinja NFTDuel card WHITELIST.",
      message2: "※ You can use this White list rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    avatar: {
      icon: close,
      openBox: open,
      title: "RARE AVATAR ITEM",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won “Rare Avatar Item”`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      greet: "Congratulations !",
      title1: "",
      message1: " You had won IN-APP CURRENCY.",
      message2:
        "※ An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  7: {
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: "You had won XANA:Genesis",
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: "",
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    cryptoNinjaNftDuelPack: {
      icon: close,
      openBox: open,
      title: "CRYPTONINJA",
      title1: "NFTDuel card pack",
      cycle: "7",
      greet: "Congratulations !",
      message1: " You had won CryptoNinja NFTDuel card Pack.",
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    cryptoNinjaNftDuelWhiteList: {
      icon: close,
      openBox: open,
      title: "CRYPTONINJA",
      title1: "NFTDuel card Whitelist",
      greet: "Congratulations !",
      message1: ` You had won "CryptoNinja NFTDuel card WHITELIST".`,
      message2: "* You can use this Whitelist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDualCard: {
      icon: close,
      openBox: open,
      title: "NFTDuel SINGLE CARD",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel single card”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz."`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      greet: "Congratulations !",
      title1: "",
      message1: " You had won IN-APP CURRENCY.",
      message2:
        "* An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  8: {
    xanaPenpenzAllowlist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "Allowlist",
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2: "* You can use this Whitelist rights for the Official mint.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: ``,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "(Type-A)",
      cycle: "8",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz (Type-A)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this Whitelist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "(Type-B)",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables (Type-B)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xtoken: {
      icon: close,
      openBox: open,
      title: "IN-APP CURRENCY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "In-App currency".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  9: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:Genesis",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: ``,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "(Type-A)",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz (Type-A)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this Whitelist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "(Type-B)",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables (Type-B)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  10: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: ``,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "(Type-A)",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz (Type-A)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this Whitelist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "(Type-B)",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables (Type-B)".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  11: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:PENPENZ WHITELIST.",
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this Whitelist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  12: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:PENPENZ".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this Whitelist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  13: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:PENPENZ".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    NFTDuelCardAllowlist: {
      icon: close,
      openBox: open,
      title: "NFTDuel card",
      title1: "(Allowlist)",
      greet: "Congratulations !",
      message1: `You had won "NFTDuel card (Allowlist)".`,
      message2: "*You can use this allowlist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  14: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:PENPENZ".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:GENESIS".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    KinashiFujiAllowlist: {
      icon: close,
      openBox: open,
      title: "Kinashi Fuji Allowlist",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "Kinashi Fuji Allowlist".`,
      message2: "*You can use this allowlist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
    },
  },
  15: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:PENPENZ".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    KinashiFujiAllowlist: {
      icon: close,
      openBox: open,
      title: "Kinashi Fuji Allowlist",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "Kinashi Fuji Allowlist".`,
      message2: "*You can use this allowlist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  16: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:PENPENZ".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:GENESIS".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    KinashiFujiAllowlist: {
      icon: close,
      openBox: open,
      title: "Kinashi Fuji Allowlist",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "Kinashi Fuji Allowlist".`,
      message2: "*You can use this allowlist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  17: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:PENPENZ".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:Land (COMMON)".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    KinashiFujiAllowlist: {
      icon: close,
      openBox: open,
      title: "Kinashi Fuji Allowlist",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "Kinashi Fuji Allowlist".`,
      message2: "*You can use this allowlist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  18: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:PENPENZ".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:GENESIS".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    KinashiFujiAllowlist: {
      icon: close,
      openBox: open,
      title: "Kinashi Fuji Allowlist",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "Kinashi Fuji Allowlist".`,
      message2: "*You can use this allowlist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  19: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:PENPENZ".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    genesis: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:GENESIS".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    KinashiFujiAllowlist: {
      icon: close,
      openBox: open,
      title: "Kinashi Fuji Allowlist",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "Kinashi Fuji Allowlist".`,
      message2: "*You can use this allowlist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },
  20: {
    xanaPenpenzWhitelist: {
      icon: close,
      openBox: open,
      title: "XANA:PENPENZ",
      cycle: 8,
      title1: "",
      greet: "Congratulations !",
      message1: ` You had won "XANA:PENPENZ".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 10%",
      limit: 5,
    },
    land: {
      icon: close,
      openBox: open,
      title: "XANA:Land (COMMON)",
      title1: "",
      greet: "Congratulations !",
      message1: " You had won XANA:Land (COMMON).",
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "CLAIM NOW",
      modalFor: "treasure",
    },
    xanaGenesisVoice: {
      icon: close,
      openBox: open,
      title: "XANA:GENESIS",
      title1: "Voice Plugin v1",
      greet: "Congratulations !",
      message1: `You had won "XANA:Genesis  Voice Plugin v1"`,
      message2:
        "You can select your XANA: Genesis to apply this plug-in. Note this action can’t be undone. Please wait and do not trade this XANA: Genesis for a while until we complete upgrading.",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
      stands: "TOP 30%",
      limit: 4,
    },
    xanaSneakerz: {
      icon: close,
      openBox: open,
      title: "XANA:Sneakerz ",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA:Sneakerz".`,
      message2: "Do you want to claim? (Claims must be paid for Gas Fee)",
      unstakeBtnText: "Confirm",
      modalFor: "treasure",
    },
    NFTDualPack: {
      icon: close,
      openBox: open,
      title: "NFTDuel card ",
      title1: "(pack)",
      greet: "Congratulations !",
      message1: `You had won “NFTDuel card (pack)”.`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 50%",
      limit: 3,
    },
    NFTDuelBooster: {
      icon: close,
      openBox: open,
      title: "NFTDuel booster",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "NFTDuel booster".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "Ok",
      modalFor: "treasure",
    },
    KinashiFujiAllowlist: {
      icon: close,
      openBox: open,
      title: "Kinashi Fuji Allowlist",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "Kinashi Fuji Allowlist".`,
      message2: "*You can use this allowlist rights for the Official mint",
      unstakeBtnText: "OK",
      modalFor: "treasure",
      stands: "TOP 80%",
      limit: 1,
    },
    xanaWearables: {
      icon: close,
      openBox: open,
      title: "XANA Wearables",
      title1: "",
      greet: "Congratulations !",
      message1: `You had won "XANA Wearables".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
    Xeny: {
      icon: close,
      openBox: open,
      title: "XENY",
      greet: "Congratulations !",
      title1: "",
      message1: `You had won "XENY".`,
      message2:
        "*An official announcement will be made as soon as the distribution is ready.",
      unstakeBtnText: "OK",
      modalFor: "treasure",
    },
  },

  cycles: [
    { key: "cycle20", title: "Cycle 20", cycle: "20" },
    { key: "cycle19", title: "Cycle 19", cycle: "19" },
    { key: "cycle18", title: "Cycle 18", cycle: "18" },
    { key: "cycle17", title: "Cycle 17", cycle: "17" },
    { key: "cycle16", title: "Cycle 16", cycle: "16" },
    { key: "cycle15", title: "Cycle 15", cycle: "15" },
    { key: "cycle14", title: "Cycle 14", cycle: "14" },
    { key: "cycle13", title: "Cycle 13", cycle: "13" },
    { key: "cycle12", title: "Cycle 12", cycle: "12" },
    { key: "cycle11", title: "Cycle 11", cycle: "11" },
    { key: "cycle10", title: "Cycle 10", cycle: "10" },
    { key: "cycle9", title: "Cycle 9", cycle: "9" },
    { key: "cycle8", title: "Cycle 8", cycle: "8" },
    { key: "cycle7", title: "Cycle 7", cycle: "7" },
    { key: "cycle6", title: "Cycle 6", cycle: "6" },
    { key: "cycle5", title: "Cycle 5", cycle: "5" },
    { key: "cycle4", title: "Cycle 4", cycle: "4" },
    { key: "cycle3", title: "Cycle 3", cycle: "3" },
    { key: "cycle2", title: "Cycle 2", cycle: "2" },
    { key: "cycle1", title: "Cycle 1", cycle: "1" },
  ],
};
export default allCycles;
